version: '3'
services:
  rest_api:
    image: rest_api
    container_name: rest_api
    ports:
      - 5000:5000
    networks:
      - monitoring
  prometheus:
    #image: prom/prometheus:latest
    image: prome
    container_name: prometheus
    restart: always
    ports:
      - 9090:9090
    networks:
      - monitoring
  node-exporter:
    image: prom/node-exporter
    expose:
      - 9100
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=grafana
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - monitoring
    depends_on:
      - prometheus
networks:
  monitoring:
