global:
  scrape_interval:     15s
  evaluation_interval: 10s
  scrape_timeout: 10s
scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
      - targets: ['0.0.0.0:9090', 'rest_api:5000']
  - job_name: rest_api
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ['0.0.0.0:5000']
